spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:goltracker}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:secret123}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  threads:
    virtual:
      enabled: true
