spring:
  application:
    name: gol-tracker
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: false
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    test-connection: false
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8050

gol-tracker:
  jwt:
    secret: ${JWT_SECRET:Z2FzZXN0YWRpdW1nb2x0cmFja2Vyc2VjcmV0a2V5MjAyNg==}
    expiration: 1500000             # 25 min en ms
  admin:
    email: ${ADMIN_EMAIL:wpradere@gmail.com}
  app:
    url: ${APP_URL:http://localhost:3000}

logging:
  level:
    com.goltracker: DEBUG
    org.springframework.security: WARN
    org.flywaydb: INFO
